### ISSUE TITLE
Enabling checks for clang-tidy

### ISSUE THREAD

**Issue by sorru94** [astarte-platform/astarte-device-sdk-esp32#112]
In #110 a series of checks have been disabled as they would generate warnings and block the CI.
The long-term objective is to re-enable some of those checks while fixing the generated warnings.
The list of checks that should be re-enabled is the following:
- [x] **bugprone-macro-parentheses** #139 
       Ensures macros have parenthesis around their content.
- [x] **bugprone-suspicious-string-compare** #139 
      Warns when using the result of `strncmp()` in a easy to misinterpret way.
- [x] **cert-err33-c** #150
      Forces to always use function results.
- [x] **clang-analyzer-deadcode.DeadStores** #139 
      Warns when a value is assigned to a variable but never used.
- [x] **clang-analyzer-security.insecureAPI.DeprecatedOrUnsafeBufferHandling** #139 
      ~~Identifies some obsolete and unsafe functions from the standard library~~. This check refers to functions not supported by the compiler we use, it should be ignored.
- [x] **cppcoreguidelines-init-variables**  #145
      Warns when using uninitialized variables.
- [x] **cppcoreguidelines-narrowing-conversions** #148
      Warns on narrowing implicit conversion.
- [x] **hicpp-signed-bitwise** #146
      Warns on bitwise operations on signed numbers.
- [x] **misc-unused-parameters** #147
      Warns against dangling parameters.
- [x] **readability-else-after-return** #139
      Warns against useless else after a return.
- [x] **readability-identifier-length** #149 
      Warns against too short identifiers.
- [x] **readability-identifier-naming** #151
      Sets some strict rules for naming of functions/variables/params/etc.
- [x] **readability-inconsistent-declaration-parameter-name** #139
      Warns when functions definition and declaration have different parameters names.
- [x] **readability-magic-numbers** #176 
      Warns when magic numbers are used.
- [x] **readability-uppercase-literal-suffix** #139
      Warns when using literal suffices with non-capital letters (e.g. `1u` is not ok, `1U` is ok, `1` is ok).

The following rules are aliases for some of the rules above:
- bugprone-narrowing-conversions (cppcoreguidelines-narrowing-conversions) #148
- cppcoreguidelines-avoid-magic-numbers (readability-magic-numbers) #176 
- hicpp-uppercase-literal-suffix (readability-uppercase-literal-suffix) #139
- llvm-else-after-return (readability-else-after-return) #139
